# -*- coding: utf-8 -*-
"""concat_images.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tw_pEnQyk4WOfj8QIVhr_HjvpNdQjbqW
"""

# pip3 install pillow

# load python packages
from PIL import Image, ImageOps
import os
import glob
import cv2
import numpy as np



# crop images 
def crop_concat():


    for v in range(10):

# find the image path
        content_list = ['/content/gdrive/My Drive/DeepLearning/Face_detection/test/5050M/M',
                        '/content/gdrive/My Drive/DeepLearning/Face_detection/test/5050F/F'
                      ]

        for content in content_list:
            image_list = []
            image_id = content + str(v)

            for i in range(11):
#find images with ending with".jpg_predicted.jpg" in a given directory. Change it based on your need
                images = image_id + '_' + str(i) + '.jpg_predicted.jpg'
            
                image_list.append(images)

                # append 11 images to one single image
                image = [Image.open(x) for x in image_list]

# resize image
# copied and pasted from stackoverflow
                basewidth = 750
                img = Image.open(images)
                wpercent = (basewidth / float(img.size[0]))
                hsize = int((float(img.size[1]) * float(wpercent)))
                img = img.resize((basewidth, hsize), Image.ANTIALIAS)

                new_width = 300
                new_height = 400
                new_im = Image.new('RGB', (300* 11 , 400))
                x_offset = 0

                for im in image:
                    width, height = im.size

                    left = (width - new_width) / 2
                    top = (height - new_height-30) / 2
                    right = (width + new_width) / 2
                    bottom = (height + new_height+30) / 2
                    crop_rectangle = (left, top, right, bottom)
                    im = im.crop(crop_rectangle)

                    new_im.paste(im, (x_offset, 0))
                    x_offset += im.size[0]

#save image
                new_im.save(content+'_%s.jpg' % int(v))

#print image names to double check
        print(image_list)


if __name__ == '__main__':

    crop_concat()